{"uid":"a463a0e98a57a354","name":"test_open_carcenter","fullName":"scripts.test01_open_carcenter.TestOpenCarcenter#test_open_carcenter","historyId":"90a8e1d0c1efb8009e96b4bc52d25ae5","time":{"start":1690337735103,"stop":1690337765930,"duration":30827},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (C:\\Users\\8252134\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:75:12)","statusTrace":"self = <scripts.test01_open_carcenter.TestOpenCarcenter object at 0x000002605B220B50>\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    def test_open_carcenter(self):\n        # home - 点击 车辆\n>       self.page.carcenter.click_carcenter()\n\nscripts\\test01_open_carcenter.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage\\carcenter_page.py:26: in click_carcenter\n    self.click(self.carcenter)\nbase\\base_action.py:42: in click\n    self.find_element(feature, timeout, poll).click()\nbase\\base_action.py:23: in find_element\n    return WebDriverWait(self.driver, timeout, poll).until(lambda x: x.find_element(*feature))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"60b0675f-3288-4726-b77a-e4e44c2a09f6\")>\nmethod = <function BaseAction.find_element.<locals>.<lambda> at 0x000002605B21F010>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       NoSuchElementError: An element could not be located on the page using the given search parameters.\nE           at AndroidUiautomator2Driver.findElOrEls (C:\\Users\\8252134\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)\nE           at processTicksAndRejections (node:internal/process/task_queues:95:5)\nE           at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:60:12)\nE           at AndroidUiautomator2Driver.findElement (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:75:12)\n\nC:\\Users\\8252134\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:95: TimeoutException","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":52,"retriesStatusChange":true,"beforeStages":[{"name":"_xunit_setup_method_fixture_TestOpenCarcenter","time":{"start":1690337724890,"stop":1690337735102,"duration":10212},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0}],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (C:\\Users\\8252134\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:75:12)","statusTrace":"self = <scripts.test01_open_carcenter.TestOpenCarcenter object at 0x000002605B220B50>\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    def test_open_carcenter(self):\n        # home - 点击 车辆\n>       self.page.carcenter.click_carcenter()\n\nscripts\\test01_open_carcenter.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage\\carcenter_page.py:26: in click_carcenter\n    self.click(self.carcenter)\nbase\\base_action.py:42: in click\n    self.find_element(feature, timeout, poll).click()\nbase\\base_action.py:23: in find_element\n    return WebDriverWait(self.driver, timeout, poll).until(lambda x: x.find_element(*feature))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"60b0675f-3288-4726-b77a-e4e44c2a09f6\")>\nmethod = <function BaseAction.find_element.<locals>.<lambda> at 0x000002605B21F010>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       NoSuchElementError: An element could not be located on the page using the given search parameters.\nE           at AndroidUiautomator2Driver.findElOrEls (C:\\Users\\8252134\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)\nE           at processTicksAndRejections (node:internal/process/task_queues:95:5)\nE           at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:60:12)\nE           at AndroidUiautomator2Driver.findElement (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:75:12)\n\nC:\\Users\\8252134\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:95: TimeoutException","steps":[{"name":"车辆页 - 点击 车辆","time":{"start":1690337735103,"stop":1690337765929,"duration":30826},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (C:\\Users\\8252134\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:75:12)\n","statusTrace":"  File \"C:\\Users\\8252134\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"E:\\DM\\ShirleyPytest\\page\\carcenter_page.py\", line 26, in click_carcenter\n    self.click(self.carcenter)\n  File \"E:\\DM\\ShirleyPytest\\base\\base_action.py\", line 42, in click\n    self.find_element(feature, timeout, poll).click()\n  File \"E:\\DM\\ShirleyPytest\\base\\base_action.py\", line 23, in find_element\n    return WebDriverWait(self.driver, timeout, poll).until(lambda x: x.find_element(*feature))\n  File \"C:\\Users\\8252134\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":0}],"attachments":[{"uid":"5449537b91431a18","name":"log","source":"5449537b91431a18.txt","type":"text/plain","size":206}],"parameters":[],"stepsCount":1,"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":1},"afterStages":[{"name":"_xunit_setup_method_fixture_TestOpenCarcenter::0","time":{"start":1690337765947,"stop":1690337766211,"duration":264},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0}],"labels":[{"name":"severity","value":"blocker"},{"name":"parentSuite","value":"scripts"},{"name":"suite","value":"test01_open_carcenter"},{"name":"subSuite","value":"TestOpenCarcenter"},{"name":"host","value":"H-K4E-232519"},{"name":"thread","value":"14032-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"scripts.test01_open_carcenter"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"blocker","retries":[{"uid":"2e42fac51218a033","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (C:\\Users\\8252134\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:75:12)","time":{"start":1690337694173,"stop":1690337724649,"duration":30476}},{"uid":"c62eeff769b693d","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (C:\\Users\\8252134\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:75:12)","time":{"start":1690337652099,"stop":1690337683477,"duration":31378}},{"uid":"31587893c6b7d2d8","status":"broken","statusDetails":"Exception: 没有找到，对应的feature的元素，请检查。","time":{"start":1690337544948,"stop":1690337576482,"duration":31534}},{"uid":"88749a42ca046881","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (C:\\Users\\8252134\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:75:12)","time":{"start":1690337500064,"stop":1690337530607,"duration":30543}},{"uid":"7d04a38ebb5e09c6","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (C:\\Users\\8252134\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (C:\\Users\\8252134\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\basedriver\\commands\\find.ts:75:12)","time":{"start":1690337454561,"stop":1690337485428,"duration":30867}},{"uid":"afc70e2a1e78bcd0","status":"broken","statusDetails":"Exception: 到底了！请检查传入的元素的特征","time":{"start":1690336665959,"stop":1690336700603,"duration":34644}},{"uid":"7494775338929679","status":"broken","statusDetails":"Exception: 到底了！请检查传入的元素的特征","time":{"start":1690336621474,"stop":1690336655710,"duration":34236}},{"uid":"e6ec27ba1e6b90d5","status":"broken","statusDetails":"Exception: 到底了！请检查传入的元素的特征","time":{"start":1690336576222,"stop":1690336610749,"duration":34527}},{"uid":"a8af4decf27ee581","status":"broken","statusDetails":"Exception: 到底了！请检查传入的元素的特征","time":{"start":1690336470648,"stop":1690336505340,"duration":34692}},{"uid":"a946ed9ca322dca4","status":"broken","statusDetails":"Exception: 到底了！请检查传入的元素的特征","time":{"start":1690336425812,"stop":1690336460264,"duration":34452}},{"uid":"44e72a657afef1ec","status":"broken","statusDetails":"Exception: 到底了！请检查传入的元素的特征","time":{"start":1690336380387,"stop":1690336415234,"duration":34847}},{"uid":"54ac87fef3901153","status":"broken","statusDetails":"TypeError: BaseAction.__init__() missing 1 required positional argument: 'driver'","time":{"start":1690336339939,"stop":1690336339939,"duration":0}},{"uid":"7de4f08f02d10dfa","status":"broken","statusDetails":"TypeError: BaseAction.__init__() missing 1 required positional argument: 'driver'","time":{"start":1690336333514,"stop":1690336333514,"duration":0}},{"uid":"dc6cc62a3dcf2415","status":"broken","statusDetails":"TypeError: BaseAction.__init__() missing 1 required positional argument: 'driver'","time":{"start":1690336328408,"stop":1690336328408,"duration":0}},{"uid":"b10887035ed74bef","status":"broken","statusDetails":"NameError: name 'right' is not defined","time":{"start":1690336162162,"stop":1690336162162,"duration":0}},{"uid":"ec8771ea2dcc6e09","status":"broken","statusDetails":"NameError: name 'right' is not defined","time":{"start":1690336152182,"stop":1690336152182,"duration":0}},{"uid":"13f0db60545d5bcd","status":"broken","statusDetails":"NameError: name 'right' is not defined","time":{"start":1690336142006,"stop":1690336142006,"duration":0}},{"uid":"ac28b1e0fb18b70f","status":"broken","statusDetails":"AttributeError: 'TestOpenCarcenter' object has no attribute 'initlog'","time":{"start":1690336061296,"stop":1690336061296,"duration":0}},{"uid":"1dc15c9614a80162","status":"broken","statusDetails":"AttributeError: 'TestOpenCarcenter' object has no attribute 'initlog'","time":{"start":1690336049747,"stop":1690336049747,"duration":0}},{"uid":"2aa6c10613744492","status":"broken","statusDetails":"AttributeError: 'TestOpenCarcenter' object has no attribute 'initlog'","time":{"start":1690336039768,"stop":1690336039768,"duration":0}},{"uid":"610475ed9aeab302","status":"broken","statusDetails":"Exception: 到底了！请检查传入的元素的特征","time":{"start":1690335772734,"stop":1690335842242,"duration":69508}},{"uid":"fc47b5c9ab261ca6","status":"broken","statusDetails":"TypeError: appium.webdriver.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement","time":{"start":1690335716920,"stop":1690335762638,"duration":45718}},{"uid":"cc67f93366b05e7f","status":"broken","statusDetails":"Exception: 到底了！请检查传入的元素的特征","time":{"start":1690335672531,"stop":1690335706556,"duration":34025}},{"uid":"25e5509230cb0f1d","status":"broken","statusDetails":"AttributeError: 'TestOpenCarcenter' object has no attribute 'initlog'","time":{"start":1690335403835,"stop":1690335403835,"duration":0}},{"uid":"8b11de4442f81b1d","status":"broken","statusDetails":"AttributeError: 'TestOpenCarcenter' object has no attribute 'initlog'","time":{"start":1690335392951,"stop":1690335392951,"duration":0}},{"uid":"a8a73582a5a81d20","status":"broken","statusDetails":"AttributeError: 'TestOpenCarcenter' object has no attribute 'initlog'","time":{"start":1690335378810,"stop":1690335378810,"duration":0}},{"uid":"1a96930902fbc01b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A79C38B9D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690335068510,"stop":1690335068510,"duration":0}},{"uid":"12cfd05802996bcd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A79C217700>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690335060114,"stop":1690335060114,"duration":0}},{"uid":"e0d10ec7de718215","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A79B54A350>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690335051576,"stop":1690335051576,"duration":0}},{"uid":"ba22de2a919098bc","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000287CB9CD510>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690335003967,"stop":1690335003967,"duration":0}},{"uid":"ccfcd11c51b8426d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000287CBA9ED40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334995253,"stop":1690334995253,"duration":0}},{"uid":"9520520510ce8592","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000287CAC952D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334986688,"stop":1690334986688,"duration":0}},{"uid":"640139e20c2f23c3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000011022C5CEB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334914443,"stop":1690334914443,"duration":0}},{"uid":"605e9ceb00da2069","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000011022BA5CC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334906149,"stop":1690334906149,"duration":0}},{"uid":"7647d49073a2c6fa","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000011021EAE290>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334897582,"stop":1690334897582,"duration":0}},{"uid":"46df29b33f476ab5","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED6DA75600>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334856797,"stop":1690334856797,"duration":0}},{"uid":"616a6d07262bbcfe","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED6D955C30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334848470,"stop":1690334848470,"duration":0}},{"uid":"ee205659aaac9f4c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED6CC5E290>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334839668,"stop":1690334839668,"duration":0}},{"uid":"46db9e5cb800b726","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AA7AB48F70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334522961,"stop":1690334522961,"duration":0}},{"uid":"f3f926c453d42bbc","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AA7AA95060>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334514512,"stop":1690334514512,"duration":0}},{"uid":"55c6bcc3063637a3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AA79D92C80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334505977,"stop":1690334505977,"duration":0}},{"uid":"849cfc25c62109b8","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002416C5A0A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334451826,"stop":1690334451826,"duration":0}},{"uid":"67827df19ea9b1e9","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002416CE1F670>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334443585,"stop":1690334443585,"duration":0}},{"uid":"3a875216659c7b16","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002416C14E3E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1690334434201,"stop":1690334434201,"duration":0}},{"uid":"301e81ad59895a54","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DB7BF165F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1689930428941,"stop":1689930428941,"duration":0}},{"uid":"ba5b571afe18466f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DB7BDBEB00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1689930420596,"stop":1689930420596,"duration":0}},{"uid":"d855fbad85344b4","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DB7B083610>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1689930411310,"stop":1689930411310,"duration":0}},{"uid":"2024846e641a56fa","status":"passed","time":{"start":1689668713263,"stop":1689668715098,"duration":1835}},{"uid":"e403f4451d35b6d9","status":"passed","time":{"start":1689668265079,"stop":1689668266983,"duration":1904}},{"uid":"eeb03d2988ff66e","status":"passed","time":{"start":1689667348361,"stop":1689667350466,"duration":2105}},{"uid":"db9d59a379215941","status":"passed","time":{"start":1689667119978,"stop":1689667121785,"duration":1807}},{"uid":"b3c2854dd776e587","status":"passed","time":{"start":1689665303475,"stop":1689665305085,"duration":1610}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":1,"unknown":0,"total":2},"items":[{"uid":"e936bf9bc5f6ce51","reportUrl":"http://10.223.60.25:8080/job/ShirleyWorkspaceTest/job/ShirleyPytestLocal/4/allure/#testresult/e936bf9bc5f6ce51","status":"passed","time":{"start":1689668713263,"stop":1689668715098,"duration":1835}}]},"tags":[]},"source":"a463a0e98a57a354.json","parameterValues":[]}